import type { ListingCardItem } from '@/lib/types'

export const mockListings: ListingCardItem[] = [
  {
    id: '1',
    slug: 'strandkajen-12-stockholm',
    title: 'Ljus 2:a nära vattnet',
    city: 'Stockholm',
    areaName: 'Södermalm',
    listingType: 'rent',
    propertyType: 'apartment',
    status: 'published',
    price: 14500,
    rooms: 2,
    areaSqm: 58,
    imageUrl:
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    badge: 'Verifierad annonsör',
    availableFrom: 'Omgående',
    features: ['Balkong', 'Hiss', 'Diskmaskin'],
    isVerified: true,
  },
  {
    id: '2',
    slug: 'havsutsikt-limhamn-malmo',
    title: 'Modern 3:a med havsutsikt',
    city: 'Malmö',
    areaName: 'Limhamn',
    listingType: 'rent',
    propertyType: 'apartment',
    status: 'published',
    price: 16750,
    rooms: 3,
    areaSqm: 76,
    imageUrl:
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
    badge: 'Nyinkommen',
    availableFrom: '2026-06-01',
    features: ['Garage', 'Havsutsikt', 'Tvättmaskin'],
    isVerified: false,
  },
  {
    id: '3',
    slug: 'villa-djursholm',
    title: 'Exklusiv villa i lugnt område',
    city: 'Stockholm',
    areaName: 'Djursholm',
    listingType: 'sale',
    propertyType: 'house',
    status: 'published',
    price: 12950000,
    rooms: 6,
    areaSqm: 214,
    imageUrl:
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    badge: 'Till salu',
    availableFrom: null,
    features: ['Trädgård', 'Garage', 'Terrass'],
    isVerified: true,
  },
  {
    id: '4',
    slug: 'cityetta-goteborg',
    title: 'Yteffektiv cityetta',
    city: 'Göteborg',
    areaName: 'Linné',
    listingType: 'rent',
    propertyType: 'apartment',
    status: 'published',
    price: 9800,
    rooms: 1,
    areaSqm: 31,
    imageUrl:
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
    badge: 'Hyra',
    availableFrom: '2026-05-15',
    features: ['Möblerad', 'Centralt', 'Förråd'],
    isVerified: false,
  },
  {
    id: '5',
    slug: 'radhus-uppsala',
    title: 'Familjevänligt radhus nära natur',
    city: 'Uppsala',
    areaName: 'Sunnersta',
    listingType: 'sale',
    propertyType: 'house',
    status: 'published',
    price: 4895000,
    rooms: 5,
    areaSqm: 142,
    imageUrl:
      'https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80',
    badge: 'Till salu',
    availableFrom: null,
    features: ['Uteplats', 'Parkering', 'Barnvänligt'],
    isVerified: true,
  },
  {
    id: '6',
    slug: 'nyrenoverad-tvaa-helsingborg',
    title: 'Nyrenoverad 2:a med balkong',
    city: 'Helsingborg',
    areaName: 'Olympia',
    listingType: 'rent',
    propertyType: 'apartment',
    status: 'published',
    price: 11900,
    rooms: 2,
    areaSqm: 54,
    imageUrl:
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    badge: 'Verifierad annonsör',
    availableFrom: '2026-07-01',
    features: ['Balkong', 'Nyrenoverad', 'Källarförråd'],
    isVerified: true,
  },
]