import { ListingCardItem } from '@/lib/types'

export const mockListings: ListingCardItem[] = [
  {
    id: '1',
    slug: 'strandkajen-12-stockholm',
    title: 'Ljus 2:a nära vattnet',
    city: 'Stockholm',
    areaName: 'Kungsholmen',
    listingType: 'rent',
    propertyType: 'apartment',
    price: 14850,
    rooms: 2,
    areaSqm: 58,
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    badge: 'Verifierad hyresvärd',
    availableFrom: '2026-06-01',
    features: ['Balkong', 'Hiss', 'Tvättmaskin'],
  },
  {
    id: '2',
    slug: 'parkallén-4-goteborg',
    title: 'Renoverad 3:a med öppen planlösning',
    city: 'Göteborg',
    areaName: 'Linné',
    listingType: 'sale',
    propertyType: 'apartment',
    price: 3795000,
    rooms: 3,
    areaSqm: 76,
    imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
    badge: 'Till salu',
    features: ['Balkong', 'Förråd', 'Helkaklat badrum'],
  },
  {
    id: '3',
    slug: 'ekbacken-7-malmo',
    title: 'Familjevilla med trädgård',
    city: 'Malmö',
    areaName: 'Limhamn',
    listingType: 'sale',
    propertyType: 'house',
    price: 6495000,
    rooms: 6,
    areaSqm: 162,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    badge: 'Populärt område',
    features: ['Trädgård', 'Garage', 'Uteplats'],
  },
  {
    id: '4',
    slug: 'stationsgatan-18-uppsala',
    title: 'Central hyresrätt med snabb inflytt',
    city: 'Uppsala',
    areaName: 'Centrum',
    listingType: 'rent',
    propertyType: 'apartment',
    price: 11200,
    rooms: 1,
    areaSqm: 39,
    imageUrl: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
    badge: 'Snabb inflytt',
    availableFrom: '2026-05-15',
    features: ['Nära pendling', 'Nyrenoverad', 'Fiber'],
  },
  {
    id: '5',
    slug: 'sodra-hamnen-22-helsingborg',
    title: 'Modern 4:a med havsutsikt',
    city: 'Helsingborg',
    areaName: 'Södra Hamnen',
    listingType: 'sale',
    propertyType: 'apartment',
    price: 5295000,
    rooms: 4,
    areaSqm: 103,
    imageUrl: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80',
    badge: 'Premium',
    features: ['Havsutsikt', 'Balkong', 'Garageplats'],
  },
  {
    id: '6',
    slug: 'solrosvagen-3-linkoping',
    title: 'Välplanerad 2:a i lugnt område',
    city: 'Linköping',
    areaName: 'Vallastaden',
    listingType: 'rent',
    propertyType: 'apartment',
    price: 9950,
    rooms: 2,
    areaSqm: 54,
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    badge: 'Hög matchning',
    availableFrom: '2026-06-15',
    features: ['Diskmaskin', 'Balkong', 'Förråd'],
  },
]

export const areaHighlights = [
  { name: 'Stockholm', count: '420+ objekt', description: 'Premiumområden, citynära hyresrätter och attraktiva bostäder till salu.' },
  { name: 'Göteborg', count: '180+ objekt', description: 'Starka citylägen, snabba pendlingsstråk och välbyggda områden.' },
  { name: 'Malmö', count: '145+ objekt', description: 'Hög efterfrågan, modern produktion och stark tillväxt.' },
]

export const stats = [
  { value: '1.2k+', label: 'Aktiva objekt' },
  { value: '92%', label: 'Fyllda profiler återanvänds' },
  { value: '3.8x', label: 'Snabbare ansökningar' },
  { value: '24h', label: 'Mål för första respons' },
]
