// Generated by the Supabase MCP (generate_typescript_types) from the live
// Bovaro project schema. Do not edit by hand.
//
// Regenerate after every migration:
//   npx supabase gen types typescript --project-id <project-id> --schema public > lib/supabase/database.types.ts
// or via the Supabase MCP generate_typescript_types tool.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admin_audit_logs: {
        Row: {
          action: string
          admin_user_id: string | null
          created_at: string
          id: string
          metadata: Json
          target_id: string | null
          target_type: string
        }
        Insert: {
          action: string
          admin_user_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_type: string
        }
        Update: {
          action?: string
          admin_user_id?: string | null
          created_at?: string
          id?: string
          metadata?: Json
          target_id?: string | null
          target_type?: string
        }
        Relationships: []
      }
      admin_user_invites: {
        Row: {
          accepted_at: string | null
          accepted_by: string | null
          account_type: string
          created_at: string
          email: string
          id: string
          invited_by: string | null
          note: string | null
          role: Database["public"]["Enums"]["app_role"]
          status: string
          updated_at: string
        }
        Insert: {
          accepted_at?: string | null
          accepted_by?: string | null
          account_type?: string
          created_at?: string
          email: string
          id?: string
          invited_by?: string | null
          note?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          status?: string
          updated_at?: string
        }
        Update: {
          accepted_at?: string | null
          accepted_by?: string | null
          account_type?: string
          created_at?: string
          email?: string
          id?: string
          invited_by?: string | null
          note?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
      application_profile_snapshots: {
        Row: {
          application_id: string
          created_at: string
          id: string
          snapshot: Json
          snapshot_version: number
          user_id: string
        }
        Insert: {
          application_id: string
          created_at?: string
          id?: string
          snapshot: Json
          snapshot_version?: number
          user_id: string
        }
        Update: {
          application_id?: string
          created_at?: string
          id?: string
          snapshot?: Json
          snapshot_version?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_profile_snapshots_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "rental_applications"
            referencedColumns: ["id"]
          },
        ]
      }
      co_applicants: {
        Row: {
          accepted_at: string | null
          consented_at: string | null
          created_at: string
          email: string | null
          full_name: string
          id: string
          invite_status: string
          invite_token: string | null
          invited_at: string | null
          invited_user_id: string | null
          phone: string | null
          relationship: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          accepted_at?: string | null
          consented_at?: string | null
          created_at?: string
          email?: string | null
          full_name: string
          id?: string
          invite_status?: string
          invite_token?: string | null
          invited_at?: string | null
          invited_user_id?: string | null
          phone?: string | null
          relationship?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          accepted_at?: string | null
          consented_at?: string | null
          created_at?: string
          email?: string | null
          full_name?: string
          id?: string
          invite_status?: string
          invite_token?: string | null
          invited_at?: string | null
          invited_user_id?: string | null
          phone?: string | null
          relationship?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      companies: {
        Row: {
          business_purpose: string
          city: string | null
          company_type: string
          created_at: string
          created_by: string | null
          email: string | null
          id: string
          legal_form: string
          name: string
          org_number: string | null
          organization_number: string | null
          phone: string | null
          slug: string
          updated_at: string
          verification_note: string | null
          verification_status: string
          verified_at: string | null
          verified_by: string | null
          website: string | null
        }
        Insert: {
          business_purpose?: string
          city?: string | null
          company_type?: string
          created_at?: string
          created_by?: string | null
          email?: string | null
          id?: string
          legal_form?: string
          name: string
          org_number?: string | null
          organization_number?: string | null
          phone?: string | null
          slug: string
          updated_at?: string
          verification_note?: string | null
          verification_status?: string
          verified_at?: string | null
          verified_by?: string | null
          website?: string | null
        }
        Update: {
          business_purpose?: string
          city?: string | null
          company_type?: string
          created_at?: string
          created_by?: string | null
          email?: string | null
          id?: string
          legal_form?: string
          name?: string
          org_number?: string | null
          organization_number?: string | null
          phone?: string | null
          slug?: string
          updated_at?: string
          verification_note?: string | null
          verification_status?: string
          verified_at?: string | null
          verified_by?: string | null
          website?: string | null
        }
        Relationships: []
      }
      company_members: {
        Row: {
          company_id: string
          created_at: string
          id: string
          role: Database["public"]["Enums"]["app_role"]
          title: string | null
          user_id: string
        }
        Insert: {
          company_id: string
          created_at?: string
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          title?: string | null
          user_id: string
        }
        Update: {
          company_id?: string
          created_at?: string
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          title?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "company_members_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      document_access_logs: {
        Row: {
          access_type: string
          actor_user_id: string | null
          application_document_id: string | null
          created_at: string
          document_id: string | null
          id: string
          metadata: Json
          owner_user_id: string | null
        }
        Insert: {
          access_type: string
          actor_user_id?: string | null
          application_document_id?: string | null
          created_at?: string
          document_id?: string | null
          id?: string
          metadata?: Json
          owner_user_id?: string | null
        }
        Update: {
          access_type?: string
          actor_user_id?: string | null
          application_document_id?: string | null
          created_at?: string
          document_id?: string | null
          id?: string
          metadata?: Json
          owner_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "document_access_logs_application_document_id_fkey"
            columns: ["application_document_id"]
            isOneToOne: false
            referencedRelation: "rental_application_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "document_access_logs_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "profile_documents"
            referencedColumns: ["id"]
          },
        ]
      }
      document_reviews: {
        Row: {
          created_at: string
          decision: string
          document_id: string
          id: string
          reason: string | null
          reviewer_id: string | null
        }
        Insert: {
          created_at?: string
          decision: string
          document_id: string
          id?: string
          reason?: string | null
          reviewer_id?: string | null
        }
        Update: {
          created_at?: string
          decision?: string
          document_id?: string
          id?: string
          reason?: string | null
          reviewer_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "document_reviews_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "profile_documents"
            referencedColumns: ["id"]
          },
        ]
      }
      favorites: {
        Row: {
          created_at: string
          id: string
          listing_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          listing_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          listing_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "favorites_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      guarantors: {
        Row: {
          created_at: string
          email: string | null
          full_name: string
          id: string
          monthly_income: number | null
          note: string | null
          phone: string | null
          relationship: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          full_name: string
          id?: string
          monthly_income?: number | null
          note?: string | null
          phone?: string | null
          relationship?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          email?: string | null
          full_name?: string
          id?: string
          monthly_income?: number | null
          note?: string | null
          phone?: string | null
          relationship?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      identity_verification_events: {
        Row: {
          created_at: string
          event_type: string
          id: string
          payload: Json
          user_id: string
          verification_id: string
        }
        Insert: {
          created_at?: string
          event_type: string
          id?: string
          payload?: Json
          user_id: string
          verification_id: string
        }
        Update: {
          created_at?: string
          event_type?: string
          id?: string
          payload?: Json
          user_id?: string
          verification_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "identity_verification_events_verification_id_fkey"
            columns: ["verification_id"]
            isOneToOne: false
            referencedRelation: "identity_verifications"
            referencedColumns: ["id"]
          },
        ]
      }
      identity_verifications: {
        Row: {
          age_verified: boolean | null
          birth_date: string | null
          created_at: string
          failure_reason: string | null
          full_name_from_provider: string | null
          id: string
          metadata: Json
          personal_identity_number_hash: string | null
          provider: string
          provider_session_id: string | null
          status: Database["public"]["Enums"]["identity_verification_status"]
          updated_at: string
          user_id: string
          verified_at: string | null
        }
        Insert: {
          age_verified?: boolean | null
          birth_date?: string | null
          created_at?: string
          failure_reason?: string | null
          full_name_from_provider?: string | null
          id?: string
          metadata?: Json
          personal_identity_number_hash?: string | null
          provider: string
          provider_session_id?: string | null
          status?: Database["public"]["Enums"]["identity_verification_status"]
          updated_at?: string
          user_id: string
          verified_at?: string | null
        }
        Update: {
          age_verified?: boolean | null
          birth_date?: string | null
          created_at?: string
          failure_reason?: string | null
          full_name_from_provider?: string | null
          id?: string
          metadata?: Json
          personal_identity_number_hash?: string | null
          provider?: string
          provider_session_id?: string | null
          status?: Database["public"]["Enums"]["identity_verification_status"]
          updated_at?: string
          user_id?: string
          verified_at?: string | null
        }
        Relationships: []
      }
      legal_acceptances: {
        Row: {
          accepted_at: string
          document_type: string
          document_version: string
          id: string
          metadata: Json
          user_id: string
        }
        Insert: {
          accepted_at?: string
          document_type: string
          document_version: string
          id?: string
          metadata?: Json
          user_id: string
        }
        Update: {
          accepted_at?: string
          document_type?: string
          document_version?: string
          id?: string
          metadata?: Json
          user_id?: string
        }
        Relationships: []
      }
      listing_activity_events: {
        Row: {
          actor_user_id: string | null
          created_at: string
          event_type: string
          id: string
          listing_id: string
          message: string | null
          payload: Json
        }
        Insert: {
          actor_user_id?: string | null
          created_at?: string
          event_type: string
          id?: string
          listing_id: string
          message?: string | null
          payload?: Json
        }
        Update: {
          actor_user_id?: string | null
          created_at?: string
          event_type?: string
          id?: string
          listing_id?: string
          message?: string | null
          payload?: Json
        }
        Relationships: [
          {
            foreignKeyName: "listing_activity_events_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_documents: {
        Row: {
          created_at: string
          document_type: string
          file_name: string
          file_url: string
          id: string
          listing_id: string
        }
        Insert: {
          created_at?: string
          document_type?: string
          file_name: string
          file_url: string
          id?: string
          listing_id: string
        }
        Update: {
          created_at?: string
          document_type?: string
          file_name?: string
          file_url?: string
          id?: string
          listing_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_documents_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_features: {
        Row: {
          created_at: string
          feature_key: string
          feature_label: string
          id: string
          listing_id: string
        }
        Insert: {
          created_at?: string
          feature_key: string
          feature_label: string
          id?: string
          listing_id: string
        }
        Update: {
          created_at?: string
          feature_key?: string
          feature_label?: string
          id?: string
          listing_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_features_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_images: {
        Row: {
          alt_text: string | null
          created_at: string
          id: string
          image_url: string
          is_cover: boolean
          listing_id: string
          position: number
        }
        Insert: {
          alt_text?: string | null
          created_at?: string
          id?: string
          image_url: string
          is_cover?: boolean
          listing_id: string
          position?: number
        }
        Update: {
          alt_text?: string | null
          created_at?: string
          id?: string
          image_url?: string
          is_cover?: boolean
          listing_id?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "listing_images_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_inquiries: {
        Row: {
          created_at: string
          id: string
          inquiry_type: Database["public"]["Enums"]["inquiry_type"]
          internal_note: string | null
          landlord_company_id: string | null
          landlord_user_id: string | null
          listing_city: string
          listing_id: string | null
          listing_price: number
          listing_segment: Database["public"]["Enums"]["listing_segment"]
          listing_slug: string
          listing_title: string
          listing_type: Database["public"]["Enums"]["listing_type"]
          message: string | null
          preferred_contact_method: string | null
          requester_company_name: string | null
          requester_email: string
          requester_full_name: string
          requester_phone: string | null
          status: Database["public"]["Enums"]["inquiry_status"]
          status_updated_at: string | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          inquiry_type?: Database["public"]["Enums"]["inquiry_type"]
          internal_note?: string | null
          landlord_company_id?: string | null
          landlord_user_id?: string | null
          listing_city: string
          listing_id?: string | null
          listing_price?: number
          listing_segment: Database["public"]["Enums"]["listing_segment"]
          listing_slug: string
          listing_title: string
          listing_type: Database["public"]["Enums"]["listing_type"]
          message?: string | null
          preferred_contact_method?: string | null
          requester_company_name?: string | null
          requester_email: string
          requester_full_name: string
          requester_phone?: string | null
          status?: Database["public"]["Enums"]["inquiry_status"]
          status_updated_at?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          inquiry_type?: Database["public"]["Enums"]["inquiry_type"]
          internal_note?: string | null
          landlord_company_id?: string | null
          landlord_user_id?: string | null
          listing_city?: string
          listing_id?: string | null
          listing_price?: number
          listing_segment?: Database["public"]["Enums"]["listing_segment"]
          listing_slug?: string
          listing_title?: string
          listing_type?: Database["public"]["Enums"]["listing_type"]
          message?: string | null
          preferred_contact_method?: string | null
          requester_company_name?: string | null
          requester_email?: string
          requester_full_name?: string
          requester_phone?: string | null
          status?: Database["public"]["Enums"]["inquiry_status"]
          status_updated_at?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "listing_inquiries_landlord_company_id_fkey"
            columns: ["landlord_company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "listing_inquiries_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listing_internal_notes: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          listing_id: string
          note: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          listing_id: string
          note: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          listing_id?: string
          note?: string
        }
        Relationships: [
          {
            foreignKeyName: "listing_internal_notes_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      listings: {
        Row: {
          access_24_7: boolean
          annual_income: number | null
          application_deadline: string | null
          area_name: string | null
          area_sqm: number | null
          available_from: string | null
          build_year: number | null
          business_purpose: string | null
          cap_rate: number | null
          city: string
          commercial_type: Database["public"]["Enums"]["commercial_type"] | null
          company_id: string | null
          country: string
          created_at: string
          created_by: string | null
          description: string | null
          floor: string | null
          has_accessibility: boolean
          has_balcony: boolean
          has_building_rights: boolean
          has_camera_surveillance: boolean
          has_detail_plan: boolean
          has_electricity: boolean
          has_elevator: boolean
          has_elevator_access: boolean
          has_ev_charger: boolean
          has_loading_zone: boolean
          has_parking: boolean
          has_reception: boolean
          has_road_access: boolean
          has_water_sewer: boolean
          hide_exact_address: boolean
          id: string
          investment_type: Database["public"]["Enums"]["investment_type"] | null
          is_furnished: boolean
          is_garage: boolean
          is_heated: boolean
          is_senior_housing: boolean
          is_short_term: boolean
          is_student_housing: boolean
          is_vat_applicable: boolean
          is_verified: boolean
          land_type: Database["public"]["Enums"]["land_type"] | null
          latitude: number | null
          listing_purpose: Database["public"]["Enums"]["listing_type"] | null
          listing_segment: Database["public"]["Enums"]["listing_segment"]
          listing_type: Database["public"]["Enums"]["listing_type"]
          longitude: number | null
          max_vehicle_height_cm: number | null
          meeting_rooms: number | null
          min_lease_months: number | null
          monthly_fee: number | null
          monthly_service_fee: number | null
          occupancy_rate: number | null
          operating_cost: number | null
          parking_type: Database["public"]["Enums"]["parking_type"] | null
          pets_allowed: boolean
          policy_summary: string | null
          price: number
          price_per_sqm: number | null
          property_type: Database["public"]["Enums"]["property_type"]
          published_at: string | null
          rooms: number | null
          show_applicant_count: boolean
          slug: string
          status: Database["public"]["Enums"]["listing_status"]
          storage_type: Database["public"]["Enums"]["storage_type"] | null
          street: string | null
          title: string
          units_count: number | null
          updated_at: string
          vacancy_rate: number | null
          viewing_info: string | null
          workplaces: number | null
          zip_code: string | null
        }
        Insert: {
          access_24_7?: boolean
          annual_income?: number | null
          application_deadline?: string | null
          area_name?: string | null
          area_sqm?: number | null
          available_from?: string | null
          build_year?: number | null
          business_purpose?: string | null
          cap_rate?: number | null
          city: string
          commercial_type?:
            | Database["public"]["Enums"]["commercial_type"]
            | null
          company_id?: string | null
          country?: string
          created_at?: string
          created_by?: string | null
          description?: string | null
          floor?: string | null
          has_accessibility?: boolean
          has_balcony?: boolean
          has_building_rights?: boolean
          has_camera_surveillance?: boolean
          has_detail_plan?: boolean
          has_electricity?: boolean
          has_elevator?: boolean
          has_elevator_access?: boolean
          has_ev_charger?: boolean
          has_loading_zone?: boolean
          has_parking?: boolean
          has_reception?: boolean
          has_road_access?: boolean
          has_water_sewer?: boolean
          hide_exact_address?: boolean
          id?: string
          investment_type?:
            | Database["public"]["Enums"]["investment_type"]
            | null
          is_furnished?: boolean
          is_garage?: boolean
          is_heated?: boolean
          is_senior_housing?: boolean
          is_short_term?: boolean
          is_student_housing?: boolean
          is_vat_applicable?: boolean
          is_verified?: boolean
          land_type?: Database["public"]["Enums"]["land_type"] | null
          latitude?: number | null
          listing_purpose?: Database["public"]["Enums"]["listing_type"] | null
          listing_segment?: Database["public"]["Enums"]["listing_segment"]
          listing_type: Database["public"]["Enums"]["listing_type"]
          longitude?: number | null
          max_vehicle_height_cm?: number | null
          meeting_rooms?: number | null
          min_lease_months?: number | null
          monthly_fee?: number | null
          monthly_service_fee?: number | null
          occupancy_rate?: number | null
          operating_cost?: number | null
          parking_type?: Database["public"]["Enums"]["parking_type"] | null
          pets_allowed?: boolean
          policy_summary?: string | null
          price?: number
          price_per_sqm?: number | null
          property_type: Database["public"]["Enums"]["property_type"]
          published_at?: string | null
          rooms?: number | null
          show_applicant_count?: boolean
          slug: string
          status?: Database["public"]["Enums"]["listing_status"]
          storage_type?: Database["public"]["Enums"]["storage_type"] | null
          street?: string | null
          title: string
          units_count?: number | null
          updated_at?: string
          vacancy_rate?: number | null
          viewing_info?: string | null
          workplaces?: number | null
          zip_code?: string | null
        }
        Update: {
          access_24_7?: boolean
          annual_income?: number | null
          application_deadline?: string | null
          area_name?: string | null
          area_sqm?: number | null
          available_from?: string | null
          build_year?: number | null
          business_purpose?: string | null
          cap_rate?: number | null
          city?: string
          commercial_type?:
            | Database["public"]["Enums"]["commercial_type"]
            | null
          company_id?: string | null
          country?: string
          created_at?: string
          created_by?: string | null
          description?: string | null
          floor?: string | null
          has_accessibility?: boolean
          has_balcony?: boolean
          has_building_rights?: boolean
          has_camera_surveillance?: boolean
          has_detail_plan?: boolean
          has_electricity?: boolean
          has_elevator?: boolean
          has_elevator_access?: boolean
          has_ev_charger?: boolean
          has_loading_zone?: boolean
          has_parking?: boolean
          has_reception?: boolean
          has_road_access?: boolean
          has_water_sewer?: boolean
          hide_exact_address?: boolean
          id?: string
          investment_type?:
            | Database["public"]["Enums"]["investment_type"]
            | null
          is_furnished?: boolean
          is_garage?: boolean
          is_heated?: boolean
          is_senior_housing?: boolean
          is_short_term?: boolean
          is_student_housing?: boolean
          is_vat_applicable?: boolean
          is_verified?: boolean
          land_type?: Database["public"]["Enums"]["land_type"] | null
          latitude?: number | null
          listing_purpose?: Database["public"]["Enums"]["listing_type"] | null
          listing_segment?: Database["public"]["Enums"]["listing_segment"]
          listing_type?: Database["public"]["Enums"]["listing_type"]
          longitude?: number | null
          max_vehicle_height_cm?: number | null
          meeting_rooms?: number | null
          min_lease_months?: number | null
          monthly_fee?: number | null
          monthly_service_fee?: number | null
          occupancy_rate?: number | null
          operating_cost?: number | null
          parking_type?: Database["public"]["Enums"]["parking_type"] | null
          pets_allowed?: boolean
          policy_summary?: string | null
          price?: number
          price_per_sqm?: number | null
          property_type?: Database["public"]["Enums"]["property_type"]
          published_at?: string | null
          rooms?: number | null
          show_applicant_count?: boolean
          slug?: string
          status?: Database["public"]["Enums"]["listing_status"]
          storage_type?: Database["public"]["Enums"]["storage_type"] | null
          street?: string | null
          title?: string
          units_count?: number | null
          updated_at?: string
          vacancy_rate?: number | null
          viewing_info?: string | null
          workplaces?: number | null
          zip_code?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "listings_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          read_at: string | null
          title: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          read_at?: string | null
          title: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          read_at?: string | null
          title?: string
          user_id?: string
        }
        Relationships: []
      }
      privacy_requests: {
        Row: {
          created_at: string
          handled_at: string | null
          handled_by: string | null
          id: string
          message: string | null
          request_type: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          handled_at?: string | null
          handled_by?: string | null
          id?: string
          message?: string | null
          request_type: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          handled_at?: string | null
          handled_by?: string | null
          id?: string
          message?: string | null
          request_type?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      profile_documents: {
        Row: {
          created_at: string
          document_expires_at: string | null
          document_status: string
          document_type: string
          file_name: string
          file_url: string
          id: string
          is_default_for_applications: boolean
          rejection_reason: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          document_expires_at?: string | null
          document_status?: string
          document_type?: string
          file_name: string
          file_url: string
          id?: string
          is_default_for_applications?: boolean
          rejection_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          document_expires_at?: string | null
          document_status?: string
          document_type?: string
          file_name?: string
          file_url?: string
          id?: string
          is_default_for_applications?: boolean
          rejection_reason?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          account_type: string
          avatar_url: string | null
          city: string | null
          created_at: string
          current_housing_situation: string | null
          desired_locations: string[] | null
          desired_move_in: string | null
          employer_name: string | null
          employment_status: string | null
          first_name: string | null
          guarantor_available: boolean
          has_pets: boolean
          household_size: number | null
          id: string
          identity_verified_at: string | null
          income_type: string | null
          last_name: string | null
          marketing_consent: boolean
          monthly_income: number | null
          onboarding_completed: boolean
          personal_identity_consent_at: string | null
          personal_identity_number: string | null
          personal_letter: string | null
          phone: string | null
          phone_verified_at: string | null
          preferred_listing_intent: string
          privacy_accepted_at: string | null
          role: Database["public"]["Enums"]["app_role"]
          smoking: boolean
          study_status: string | null
          terms_accepted_at: string | null
          updated_at: string
        }
        Insert: {
          account_type?: string
          avatar_url?: string | null
          city?: string | null
          created_at?: string
          current_housing_situation?: string | null
          desired_locations?: string[] | null
          desired_move_in?: string | null
          employer_name?: string | null
          employment_status?: string | null
          first_name?: string | null
          guarantor_available?: boolean
          has_pets?: boolean
          household_size?: number | null
          id: string
          identity_verified_at?: string | null
          income_type?: string | null
          last_name?: string | null
          marketing_consent?: boolean
          monthly_income?: number | null
          onboarding_completed?: boolean
          personal_identity_consent_at?: string | null
          personal_identity_number?: string | null
          personal_letter?: string | null
          phone?: string | null
          phone_verified_at?: string | null
          preferred_listing_intent?: string
          privacy_accepted_at?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          smoking?: boolean
          study_status?: string | null
          terms_accepted_at?: string | null
          updated_at?: string
        }
        Update: {
          account_type?: string
          avatar_url?: string | null
          city?: string | null
          created_at?: string
          current_housing_situation?: string | null
          desired_locations?: string[] | null
          desired_move_in?: string | null
          employer_name?: string | null
          employment_status?: string | null
          first_name?: string | null
          guarantor_available?: boolean
          has_pets?: boolean
          household_size?: number | null
          id?: string
          identity_verified_at?: string | null
          income_type?: string | null
          last_name?: string | null
          marketing_consent?: boolean
          monthly_income?: number | null
          onboarding_completed?: boolean
          personal_identity_consent_at?: string | null
          personal_identity_number?: string | null
          personal_letter?: string | null
          phone?: string | null
          phone_verified_at?: string | null
          preferred_listing_intent?: string
          privacy_accepted_at?: string | null
          role?: Database["public"]["Enums"]["app_role"]
          smoking?: boolean
          study_status?: string | null
          terms_accepted_at?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      queue_memberships: {
        Row: {
          created_at: string
          current_points: number
          id: string
          joined_queue_at: string | null
          last_point_awarded_at: string | null
          membership_status: Database["public"]["Enums"]["queue_membership_status"]
          months_in_queue: number
          next_billing_at: string | null
          points_reset_at: string | null
          queue_type: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          current_points?: number
          id?: string
          joined_queue_at?: string | null
          last_point_awarded_at?: string | null
          membership_status?: Database["public"]["Enums"]["queue_membership_status"]
          months_in_queue?: number
          next_billing_at?: string | null
          points_reset_at?: string | null
          queue_type?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          current_points?: number
          id?: string
          joined_queue_at?: string | null
          last_point_awarded_at?: string | null
          membership_status?: Database["public"]["Enums"]["queue_membership_status"]
          months_in_queue?: number
          next_billing_at?: string | null
          points_reset_at?: string | null
          queue_type?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      queue_point_ledger: {
        Row: {
          balance_after: number
          created_at: string
          event_type: Database["public"]["Enums"]["queue_point_event_type"]
          id: string
          membership_id: string
          note: string | null
          points_delta: number
          user_id: string
        }
        Insert: {
          balance_after?: number
          created_at?: string
          event_type: Database["public"]["Enums"]["queue_point_event_type"]
          id?: string
          membership_id: string
          note?: string | null
          points_delta?: number
          user_id: string
        }
        Update: {
          balance_after?: number
          created_at?: string
          event_type?: Database["public"]["Enums"]["queue_point_event_type"]
          id?: string
          membership_id?: string
          note?: string | null
          points_delta?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "queue_point_ledger_membership_id_fkey"
            columns: ["membership_id"]
            isOneToOne: false
            referencedRelation: "queue_memberships"
            referencedColumns: ["id"]
          },
        ]
      }
      rate_limit_events: {
        Row: {
          created_at: string
          id: string
          ip_hash: string | null
          scope: string
          subject_hash: string
        }
        Insert: {
          created_at?: string
          id?: string
          ip_hash?: string | null
          scope: string
          subject_hash: string
        }
        Update: {
          created_at?: string
          id?: string
          ip_hash?: string | null
          scope?: string
          subject_hash?: string
        }
        Relationships: []
      }
      rental_application_co_applicants: {
        Row: {
          application_id: string
          created_at: string
          email: string | null
          full_name: string
          id: string
          phone: string | null
          relationship: string | null
          user_id: string
        }
        Insert: {
          application_id: string
          created_at?: string
          email?: string | null
          full_name: string
          id?: string
          phone?: string | null
          relationship?: string | null
          user_id: string
        }
        Update: {
          application_id?: string
          created_at?: string
          email?: string | null
          full_name?: string
          id?: string
          phone?: string | null
          relationship?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "rental_application_co_applicants_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "rental_applications"
            referencedColumns: ["id"]
          },
        ]
      }
      rental_application_documents: {
        Row: {
          application_id: string
          created_at: string
          document_type: string
          file_name: string
          file_url: string
          id: string
          user_id: string
        }
        Insert: {
          application_id: string
          created_at?: string
          document_type: string
          file_name: string
          file_url: string
          id?: string
          user_id: string
        }
        Update: {
          application_id?: string
          created_at?: string
          document_type?: string
          file_name?: string
          file_url?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "rental_application_documents_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "rental_applications"
            referencedColumns: ["id"]
          },
        ]
      }
      rental_application_status_history: {
        Row: {
          actor_user_id: string | null
          application_id: string
          created_at: string
          from_status:
            | Database["public"]["Enums"]["rental_application_status"]
            | null
          id: string
          note: string | null
          to_status: Database["public"]["Enums"]["rental_application_status"]
        }
        Insert: {
          actor_user_id?: string | null
          application_id: string
          created_at?: string
          from_status?:
            | Database["public"]["Enums"]["rental_application_status"]
            | null
          id?: string
          note?: string | null
          to_status: Database["public"]["Enums"]["rental_application_status"]
        }
        Update: {
          actor_user_id?: string | null
          application_id?: string
          created_at?: string
          from_status?:
            | Database["public"]["Enums"]["rental_application_status"]
            | null
          id?: string
          note?: string | null
          to_status?: Database["public"]["Enums"]["rental_application_status"]
        }
        Relationships: [
          {
            foreignKeyName: "rental_application_status_history_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "rental_applications"
            referencedColumns: ["id"]
          },
        ]
      }
      rental_applications: {
        Row: {
          applicant_email: string | null
          applicant_full_name: string | null
          applicant_household_size: number | null
          applicant_monthly_income: number | null
          applicant_phone: string | null
          applicant_snapshot: Json | null
          applicant_user_id: string | null
          cover_letter: string | null
          created_at: string
          desired_move_in: string | null
          employer_name: string | null
          employment_status: string | null
          employment_type: string | null
          has_pets: boolean | null
          household_size: number | null
          id: string
          internal_note: string | null
          landlord_company_id: string | null
          landlord_user_id: string | null
          listing_city: string | null
          listing_id: string
          listing_image_url: string | null
          listing_price: number
          listing_slug: string | null
          listing_title: string | null
          listing_type: Database["public"]["Enums"]["listing_type"]
          message: string | null
          monthly_income: number | null
          move_in_date: string | null
          pets: boolean
          queue_joined_at_snapshot: string | null
          queue_points_snapshot: number
          smoking: boolean
          status: Database["public"]["Enums"]["rental_application_status"]
          status_updated_at: string | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          applicant_email?: string | null
          applicant_full_name?: string | null
          applicant_household_size?: number | null
          applicant_monthly_income?: number | null
          applicant_phone?: string | null
          applicant_snapshot?: Json | null
          applicant_user_id?: string | null
          cover_letter?: string | null
          created_at?: string
          desired_move_in?: string | null
          employer_name?: string | null
          employment_status?: string | null
          employment_type?: string | null
          has_pets?: boolean | null
          household_size?: number | null
          id?: string
          internal_note?: string | null
          landlord_company_id?: string | null
          landlord_user_id?: string | null
          listing_city?: string | null
          listing_id: string
          listing_image_url?: string | null
          listing_price?: number
          listing_slug?: string | null
          listing_title?: string | null
          listing_type?: Database["public"]["Enums"]["listing_type"]
          message?: string | null
          monthly_income?: number | null
          move_in_date?: string | null
          pets?: boolean
          queue_joined_at_snapshot?: string | null
          queue_points_snapshot?: number
          smoking?: boolean
          status?: Database["public"]["Enums"]["rental_application_status"]
          status_updated_at?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          applicant_email?: string | null
          applicant_full_name?: string | null
          applicant_household_size?: number | null
          applicant_monthly_income?: number | null
          applicant_phone?: string | null
          applicant_snapshot?: Json | null
          applicant_user_id?: string | null
          cover_letter?: string | null
          created_at?: string
          desired_move_in?: string | null
          employer_name?: string | null
          employment_status?: string | null
          employment_type?: string | null
          has_pets?: boolean | null
          household_size?: number | null
          id?: string
          internal_note?: string | null
          landlord_company_id?: string | null
          landlord_user_id?: string | null
          listing_city?: string | null
          listing_id?: string
          listing_image_url?: string | null
          listing_price?: number
          listing_slug?: string | null
          listing_title?: string | null
          listing_type?: Database["public"]["Enums"]["listing_type"]
          message?: string | null
          monthly_income?: number | null
          move_in_date?: string | null
          pets?: boolean
          queue_joined_at_snapshot?: string | null
          queue_points_snapshot?: number
          smoking?: boolean
          status?: Database["public"]["Enums"]["rental_application_status"]
          status_updated_at?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "rental_applications_landlord_company_id_fkey"
            columns: ["landlord_company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rental_applications_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      rental_requirements: {
        Row: {
          created_at: string
          employment_required: boolean
          listing_id: string
          min_income: number | null
          pets_allowed: boolean
          references_required: boolean
          smoking_allowed: boolean
          updated_at: string
        }
        Insert: {
          created_at?: string
          employment_required?: boolean
          listing_id: string
          min_income?: number | null
          pets_allowed?: boolean
          references_required?: boolean
          smoking_allowed?: boolean
          updated_at?: string
        }
        Update: {
          created_at?: string
          employment_required?: boolean
          listing_id?: string
          min_income?: number | null
          pets_allowed?: boolean
          references_required?: boolean
          smoking_allowed?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "rental_requirements_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: true
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      sale_leads: {
        Row: {
          created_at: string
          email: string
          full_name: string
          id: string
          listing_id: string
          message: string | null
          phone: string | null
          status: Database["public"]["Enums"]["sale_lead_status"]
          updated_at: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          email: string
          full_name: string
          id?: string
          listing_id: string
          message?: string | null
          phone?: string | null
          status?: Database["public"]["Enums"]["sale_lead_status"]
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          listing_id?: string
          message?: string | null
          phone?: string | null
          status?: Database["public"]["Enums"]["sale_lead_status"]
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sale_leads_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_search_matches: {
        Row: {
          created_at: string
          id: string
          listing_id: string
          notified_at: string | null
          saved_search_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          listing_id: string
          notified_at?: string | null
          saved_search_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          listing_id?: string
          notified_at?: string | null
          saved_search_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_search_matches_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_search_matches_saved_search_id_fkey"
            columns: ["saved_search_id"]
            isOneToOne: false
            referencedRelation: "saved_searches"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_search_notification_runs: {
        Row: {
          created_at: string
          error_message: string | null
          id: string
          matched_listing_ids: string[]
          saved_search_id: string | null
          sent_at: string | null
          status: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          error_message?: string | null
          id?: string
          matched_listing_ids?: string[]
          saved_search_id?: string | null
          sent_at?: string | null
          status?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          error_message?: string | null
          id?: string
          matched_listing_ids?: string[]
          saved_search_id?: string | null
          sent_at?: string | null
          status?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "saved_search_notification_runs_saved_search_id_fkey"
            columns: ["saved_search_id"]
            isOneToOne: false
            referencedRelation: "saved_searches"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_searches: {
        Row: {
          city: string | null
          created_at: string
          id: string
          max_price: number | null
          min_rooms: number | null
          mode: Database["public"]["Enums"]["saved_search_mode"]
          notifications_enabled: boolean
          property_type: Database["public"]["Enums"]["property_type"] | null
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          city?: string | null
          created_at?: string
          id?: string
          max_price?: number | null
          min_rooms?: number | null
          mode?: Database["public"]["Enums"]["saved_search_mode"]
          notifications_enabled?: boolean
          property_type?: Database["public"]["Enums"]["property_type"] | null
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          city?: string | null
          created_at?: string
          id?: string
          max_price?: number | null
          min_rooms?: number | null
          mode?: Database["public"]["Enums"]["saved_search_mode"]
          notifications_enabled?: boolean
          property_type?: Database["public"]["Enums"]["property_type"] | null
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      subscription_plans: {
        Row: {
          amount_sek: number
          code: string
          created_at: string
          id: string
          interval_unit: string
          is_active: boolean
          max_active_applications: number | null
          name: string
          updated_at: string
        }
        Insert: {
          amount_sek: number
          code: string
          created_at?: string
          id?: string
          interval_unit?: string
          is_active?: boolean
          max_active_applications?: number | null
          name: string
          updated_at?: string
        }
        Update: {
          amount_sek?: number
          code?: string
          created_at?: string
          id?: string
          interval_unit?: string
          is_active?: boolean
          max_active_applications?: number | null
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      user_consents: {
        Row: {
          consent_type: string
          consent_version: string
          granted: boolean
          granted_at: string
          id: string
          metadata: Json
          revoked_at: string | null
          user_id: string
        }
        Insert: {
          consent_type: string
          consent_version: string
          granted?: boolean
          granted_at?: string
          id?: string
          metadata?: Json
          revoked_at?: string | null
          user_id: string
        }
        Update: {
          consent_type?: string
          consent_version?: string
          granted?: boolean
          granted_at?: string
          id?: string
          metadata?: Json
          revoked_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      user_risk_flags: {
        Row: {
          created_at: string
          created_by: string | null
          flag_type: string
          id: string
          metadata: Json
          note: string | null
          resolved_at: string | null
          resolved_by: string | null
          severity: string
          user_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          flag_type: string
          id?: string
          metadata?: Json
          note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          severity?: string
          user_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          flag_type?: string
          id?: string
          metadata?: Json
          note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          severity?: string
          user_id?: string
        }
        Relationships: []
      }
      user_subscriptions: {
        Row: {
          cancel_at_period_end: boolean
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          id: string
          plan_code: string
          provider: string
          provider_subscription_id: string | null
          status: Database["public"]["Enums"]["subscription_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          plan_code: string
          provider?: string
          provider_subscription_id?: string | null
          status?: Database["public"]["Enums"]["subscription_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          plan_code?: string
          provider?: string
          provider_subscription_id?: string | null
          status?: Database["public"]["Enums"]["subscription_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_subscriptions_plan_code_fkey"
            columns: ["plan_code"]
            isOneToOne: false
            referencedRelation: "subscription_plans"
            referencedColumns: ["code"]
          },
        ]
      }
      viewings: {
        Row: {
          created_at: string
          created_by: string | null
          id: string
          listing_id: string
          location_note: string | null
          rental_application_id: string | null
          sale_lead_id: string | null
          scheduled_at: string
          status: Database["public"]["Enums"]["viewing_status"]
          updated_at: string
          viewing_type: Database["public"]["Enums"]["viewing_type"]
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          id?: string
          listing_id: string
          location_note?: string | null
          rental_application_id?: string | null
          sale_lead_id?: string | null
          scheduled_at: string
          status?: Database["public"]["Enums"]["viewing_status"]
          updated_at?: string
          viewing_type: Database["public"]["Enums"]["viewing_type"]
        }
        Update: {
          created_at?: string
          created_by?: string | null
          id?: string
          listing_id?: string
          location_note?: string | null
          rental_application_id?: string | null
          sale_lead_id?: string | null
          scheduled_at?: string
          status?: Database["public"]["Enums"]["viewing_status"]
          updated_at?: string
          viewing_type?: Database["public"]["Enums"]["viewing_type"]
        }
        Relationships: [
          {
            foreignKeyName: "viewings_listing_id_fkey"
            columns: ["listing_id"]
            isOneToOne: false
            referencedRelation: "listings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "viewings_rental_application_id_fkey"
            columns: ["rental_application_id"]
            isOneToOne: false
            referencedRelation: "rental_applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "viewings_sale_lead_id_fkey"
            columns: ["sale_lead_id"]
            isOneToOne: false
            referencedRelation: "sale_leads"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_adjust_queue_points: {
        Args: {
          p_delta: number
          p_joined_at?: string
          p_note: string
          p_user_id: string
        }
        Returns: Json
      }
      admin_identity_overview: {
        Args: never
        Returns: {
          age_verified: boolean
          created_at: string
          failure_reason: string
          id: string
          provider: string
          status: Database["public"]["Enums"]["identity_verification_status"]
          user_id: string
          verified_at: string
        }[]
      }
      admin_queue_overview: {
        Args: never
        Returns: {
          current_points: number
          joined_queue_at: string
          membership_id: string
          membership_status: Database["public"]["Enums"]["queue_membership_status"]
          points_reset_at: string
          queue_type: string
          user_id: string
        }[]
      }
      admin_set_queue_status: {
        Args: {
          p_note: string
          p_status: Database["public"]["Enums"]["queue_membership_status"]
          p_user_id: string
        }
        Returns: Json
      }
      admin_user_overview: {
        Args: never
        Returns: {
          account_type: string
          city: string
          created_at: string
          email: string
          first_name: string
          id: string
          last_name: string
          phone: string
          role: Database["public"]["Enums"]["app_role"]
        }[]
      }
      award_queue_points_daily: { Args: never; Returns: Json }
      check_rate_limit: {
        Args: {
          input_ip_hash: string
          input_limit: number
          input_scope: string
          input_subject_hash: string
          input_window_seconds: number
        }
        Returns: boolean
      }
      current_user_can_manage_application: {
        Args: { target_application_id: string }
        Returns: boolean
      }
      current_user_can_manage_company: {
        Args: { target_company_id: string }
        Returns: boolean
      }
      current_user_can_manage_inquiry: {
        Args: { target_inquiry_id: string }
        Returns: boolean
      }
      current_user_can_manage_listing: {
        Args: { target_listing_id: string }
        Returns: boolean
      }
      current_user_company_ids: { Args: never; Returns: string[] }
      current_user_is_admin: { Args: never; Returns: boolean }
      current_user_is_super_admin: { Args: never; Returns: boolean }
      current_user_role: {
        Args: never
        Returns: Database["public"]["Enums"]["app_role"]
      }
      estimated_queue_position: {
        Args: { p_listing_id: string }
        Returns: Json
      }
      finalize_identity_verification: {
        Args: {
          p_age_verified?: boolean
          p_birth_date?: string
          p_failure_reason?: string
          p_full_name?: string
          p_metadata?: Json
          p_pin_hash?: string
          p_status: Database["public"]["Enums"]["identity_verification_status"]
          p_verification_id: string
        }
        Returns: Json
      }
      get_co_applicant_invite: {
        Args: { p_token: string }
        Returns: {
          full_name: string
          id: string
          invite_status: string
          inviter_name: string
          relationship: string
        }[]
      }
      household_queue_points: {
        Args: never
        Returns: {
          points: number
          user_id: string
        }[]
      }
      public_listing_applicant_count: {
        Args: { p_listing_id: string }
        Returns: number
      }
      reset_queue_points: {
        Args: { p_reason: string; p_user_id: string }
        Returns: Json
      }
      respond_co_applicant_invite: {
        Args: { p_accept: boolean; p_token: string }
        Returns: Json
      }
      storage_bucket_exists: { Args: { bucket_name: string }; Returns: boolean }
    }
    Enums: {
      app_role:
        | "seeker"
        | "buyer"
        | "landlord"
        | "broker"
        | "company_admin"
        | "admin"
        | "super_admin"
      commercial_type:
        | "office"
        | "retail"
        | "restaurant"
        | "warehouse"
        | "industrial"
        | "showroom"
        | "clinic"
        | "workshop"
        | "other"
      identity_verification_status:
        | "pending"
        | "verified"
        | "failed"
        | "expired"
        | "cancelled"
      inquiry_status:
        | "new"
        | "contacted"
        | "viewing_booked"
        | "negotiating"
        | "closed"
        | "rejected"
      inquiry_type: "interest" | "viewing" | "offer_request" | "contact"
      investment_type:
        | "rental_property"
        | "commercial_property"
        | "mixed_use_property"
        | "portfolio"
        | "project_property"
        | "other"
      land_type:
        | "land_plot"
        | "industrial_land"
        | "agricultural_land"
        | "development_land"
        | "yard_space"
        | "other"
      listing_segment:
        | "residential"
        | "commercial"
        | "parking"
        | "storage"
        | "land"
        | "investment"
      listing_status:
        | "draft"
        | "published"
        | "paused"
        | "rented"
        | "sold"
        | "archived"
      listing_type: "rent" | "sale"
      parking_type:
        | "outdoor"
        | "garage"
        | "ev_charging"
        | "motorcycle"
        | "truck"
        | "other"
      property_type:
        | "apartment"
        | "house"
        | "property"
        | "commercial_space"
        | "office"
        | "parking_space"
        | "garage"
        | "storage_unit"
        | "land_plot"
        | "investment_property"
      queue_membership_status:
        | "inactive"
        | "active"
        | "paused"
        | "cancelled"
        | "expired"
      queue_point_event_type:
        | "enrolled"
        | "monthly_accrual"
        | "manual_adjustment"
        | "paused"
        | "resumed"
        | "cancelled"
        | "daily_accrual"
        | "reset"
      rental_application_status:
        | "draft"
        | "submitted"
        | "received"
        | "reviewing"
        | "qualified"
        | "reserve"
        | "viewing"
        | "offered"
        | "rejected"
        | "signed"
        | "shortlisted"
        | "withdrawn"
      sale_lead_status:
        | "new"
        | "contacted"
        | "viewing_booked"
        | "follow_up"
        | "closed"
      saved_search_mode: "rent" | "sale" | "all"
      storage_type:
        | "storage_unit"
        | "warehouse_box"
        | "mini_warehouse"
        | "pallet_space"
        | "container"
        | "other"
      subscription_status:
        | "pending"
        | "active"
        | "paused"
        | "past_due"
        | "cancelled"
        | "expired"
      viewing_status: "scheduled" | "confirmed" | "completed" | "cancelled"
      viewing_type: "rental" | "sale"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: [
        "seeker",
        "buyer",
        "landlord",
        "broker",
        "company_admin",
        "admin",
        "super_admin",
      ],
      commercial_type: [
        "office",
        "retail",
        "restaurant",
        "warehouse",
        "industrial",
        "showroom",
        "clinic",
        "workshop",
        "other",
      ],
      identity_verification_status: [
        "pending",
        "verified",
        "failed",
        "expired",
        "cancelled",
      ],
      inquiry_status: [
        "new",
        "contacted",
        "viewing_booked",
        "negotiating",
        "closed",
        "rejected",
      ],
      inquiry_type: ["interest", "viewing", "offer_request", "contact"],
      investment_type: [
        "rental_property",
        "commercial_property",
        "mixed_use_property",
        "portfolio",
        "project_property",
        "other",
      ],
      land_type: [
        "land_plot",
        "industrial_land",
        "agricultural_land",
        "development_land",
        "yard_space",
        "other",
      ],
      listing_segment: [
        "residential",
        "commercial",
        "parking",
        "storage",
        "land",
        "investment",
      ],
      listing_status: [
        "draft",
        "published",
        "paused",
        "rented",
        "sold",
        "archived",
      ],
      listing_type: ["rent", "sale"],
      parking_type: [
        "outdoor",
        "garage",
        "ev_charging",
        "motorcycle",
        "truck",
        "other",
      ],
      property_type: [
        "apartment",
        "house",
        "property",
        "commercial_space",
        "office",
        "parking_space",
        "garage",
        "storage_unit",
        "land_plot",
        "investment_property",
      ],
      queue_membership_status: [
        "inactive",
        "active",
        "paused",
        "cancelled",
        "expired",
      ],
      queue_point_event_type: [
        "enrolled",
        "monthly_accrual",
        "manual_adjustment",
        "paused",
        "resumed",
        "cancelled",
        "daily_accrual",
        "reset",
      ],
      rental_application_status: [
        "draft",
        "submitted",
        "received",
        "reviewing",
        "qualified",
        "reserve",
        "viewing",
        "offered",
        "rejected",
        "signed",
        "shortlisted",
        "withdrawn",
      ],
      sale_lead_status: [
        "new",
        "contacted",
        "viewing_booked",
        "follow_up",
        "closed",
      ],
      saved_search_mode: ["rent", "sale", "all"],
      storage_type: [
        "storage_unit",
        "warehouse_box",
        "mini_warehouse",
        "pallet_space",
        "container",
        "other",
      ],
      subscription_status: [
        "pending",
        "active",
        "paused",
        "past_due",
        "cancelled",
        "expired",
      ],
      viewing_status: ["scheduled", "confirmed", "completed", "cancelled"],
      viewing_type: ["rental", "sale"],
    },
  },
} as const
